# Generated by Django 6.0.3 on 2026-03-21 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rectificacion', 'Rectificación de Ejercicio'), ('cp', 'Ejercicio CP'), ('meme', 'Meme')], max_length=15)),
                ('descripcion', models.TextField()),
                ('contexto_rectificacion', models.TextField(blank=True, null=True)),
                ('numero_cp', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_ejercicio', models.CharField(blank=True, max_length=10, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='memes/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('aceptado', models.BooleanField(default=None, null=True)),
                ('creditos_otorgados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesor', 'Profesor')], max_length=10)),
                ('creditos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creditos', 'usuario__username'],
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado', models.BooleanField()),
                ('creditos_otorgados', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('envio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='creditos.envio')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_revision'],
            },
        ),
        migrations.CreateModel(
            name='ValorCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cp', models.CharField(max_length=10)),
                ('numero_inciso', models.CharField(max_length=10)),
                ('valor_defecto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['numero_cp', 'numero_inciso'],
                'unique_together': {('numero_cp', 'numero_inciso')},
            },
        ),
    ]
