# Generated by Django 6.0.3 on 2026-03-23 00:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorPredeterminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rectificacion', 'Rectificación'), ('cp', 'CP'), ('meme', 'Meme')], max_length=15, unique=True)),
                ('valor_defecto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.AddField(
            model_name='envio',
            name='documento_rectificacion',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='envio',
            name='envio_corregido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectificaciones', to='creditos.envio'),
        ),
    ]
